CREATE TABLE cargo (
  IDCARGO int(11) NOT NULL,
  NOMBRECARGO varchar(20),
  ESTADO bit(1),
  PRIMARY KEY (IDCARGO)
);

CREATE TABLE empleado (
  IDEMPLEADO int(11) NOT NULL,
  NOMBRE varchar(40),
  APELLIDOS varchar(40),
  SEXO char(1),
  TELEFONO char(12),
  FECHANACIMIENTO date,
  TIPDOCUMENTO char(11),
  IDCARGO int(11),
  IDUSUARIO int(11),
  PRIMARY KEY (IDEMPLEADO),
  FOREIGN KEY (IDCARGO) REFERENCES cargo(IDCARGO),
  FOREIGN KEY (IDUSUARIO) REFERENCES usuario(IDUSUARIO)
);

CREATE TABLE usuario (
  IDUSUARIO int(11) NOT NULL,
  NOMBREUSUARIO varchar(20),
  CLAVE varchar(10),
  ESTADO bit(1),
  IDCARGO int(11),
  PRIMARY KEY (IDUSUARIO),
  FOREIGN KEY (IDCARGO) REFERENCES cargo(IDCARGO)
);